-- P102 Campus Spatial Knowledge Platform V1.0 Stable Schema
-- 本檔採 additive migration：只新增缺少欄位/表/函式，不刪除既有資料。

-- 主表欄位補強
ALTER TABLE public."TblP102Space" ADD COLUMN IF NOT EXISTS "FloorMapPic" text;
ALTER TABLE public."TblP102Space" ADD COLUMN IF NOT EXISTS "CampusMapPic" text;

UPDATE public."TblP102Space"
SET "FloorMapPic" = COALESCE("FloorMapPic", "PicNo")
WHERE "FloorMapPic" IS NULL AND "PicNo" IS NOT NULL;

UPDATE public."TblP102Space"
SET "CampusMapPic" = COALESCE("CampusMapPic", "PicNo")
WHERE "CampusMapPic" IS NULL AND "PicNo" IS NOT NULL;

-- 修正第三校區校區圖規則：3A1/3B1/... -> 3ABCDEF1；3AB1 -> 3ABCDEFB1
UPDATE public."TblP102Space"
SET "CampusMapPic" = REGEXP_REPLACE("PicNo", '^3AB', '3ABCDEFB')
WHERE "PicNo" ~ '^3AB';

UPDATE public."TblP102Space"
SET "CampusMapPic" = REGEXP_REPLACE("PicNo", '^3[A-F]', '3ABCDEF')
WHERE "PicNo" ~ '^3[A-F]' AND "PicNo" !~ '^3AB';

-- 修正曾經重複替換造成的錯誤
UPDATE public."TblP102Space"
SET "CampusMapPic" = REGEXP_REPLACE("CampusMapPic", '^3ABCDEFBCDEF', '3ABCDEF')
WHERE "CampusMapPic" LIKE '3ABCDEFBCDEF%';

COMMENT ON COLUMN public."TblP102Space"."FloorMapPic" IS '樓層平面圖檔名，不含副檔名。前端讀取 jpg/{FloorMapPic}.jpg。';
COMMENT ON COLUMN public."TblP102Space"."CampusMapPic" IS '校區總覽圖檔名，不含副檔名。前端讀取 jpg/{CampusMapPic}.jpg。';

-- 多語言別名表
CREATE TABLE IF NOT EXISTS public."TblP102SpaceAlias" (
  "AliasID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SpaceNo" text NOT NULL,
  "AliasName" text NOT NULL,
  "LanguageCode" text NOT NULL DEFAULT 'zh-TW',
  "AliasType" text DEFAULT 'nickname',
  "IsActive" boolean DEFAULT true,
  "SortOrder" integer DEFAULT 0,
  "CreatedAt" timestamptz DEFAULT now(),
  "UpdatedAt" timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_TblP102SpaceAlias_SpaceNo" ON public."TblP102SpaceAlias" ("SpaceNo");
CREATE INDEX IF NOT EXISTS "idx_TblP102SpaceAlias_AliasName" ON public."TblP102SpaceAlias" ("AliasName");

-- 查詢紀錄
CREATE TABLE IF NOT EXISTS public."TblP102SearchEvents" (
  "SearchEventID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Keyword" text NOT NULL,
  "ResultCount" integer DEFAULT 0,
  "MatchedBy" text,
  "SelectedSpaceNo" text,
  "CreatedAt" timestamptz DEFAULT now()
);

-- 查詢失敗紀錄
CREATE TABLE IF NOT EXISTS public."TblP102SearchFailures" (
  "FailureID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Keyword" text NOT NULL,
  "CreatedAt" timestamptz DEFAULT now()
);

-- 空間點閱紀錄
CREATE TABLE IF NOT EXISTS public."TblP102SpaceViewEvents" (
  "EventID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SpaceNo" text,
  "SpaceName" text,
  "CampusNo" text,
  "FloorMapPic" text,
  "CampusMapPic" text,
  "CreatedAt" timestamptz DEFAULT now()
);

-- 使用者回饋
CREATE TABLE IF NOT EXISTS public."TblP102Feedback" (
  "FeedbackID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "SpaceNo" text,
  "SpaceName" text,
  "FeedbackType" text,
  "FeedbackText" text NOT NULL,
  "IsReviewed" boolean DEFAULT false,
  "CreatedAt" timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "idx_TblP102SearchEvents_Keyword" ON public."TblP102SearchEvents" ("Keyword");
CREATE INDEX IF NOT EXISTS "idx_TblP102SearchFailures_Keyword" ON public."TblP102SearchFailures" ("Keyword");
CREATE INDEX IF NOT EXISTS "idx_TblP102SpaceViewEvents_SpaceNo" ON public."TblP102SpaceViewEvents" ("SpaceNo");
CREATE INDEX IF NOT EXISTS "idx_TblP102Feedback_SpaceNo" ON public."TblP102Feedback" ("SpaceNo");

-- RLS
ALTER TABLE public."TblP102Space" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP102SpaceAlias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP102SearchEvents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP102SearchFailures" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP102SpaceViewEvents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TblP102Feedback" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "P102 space public read active" ON public."TblP102Space";
CREATE POLICY "P102 space public read active" ON public."TblP102Space"
FOR SELECT TO anon USING (COALESCE("IsActive", true) = true);

DROP POLICY IF EXISTS "P102 alias public read active" ON public."TblP102SpaceAlias";
CREATE POLICY "P102 alias public read active" ON public."TblP102SpaceAlias"
FOR SELECT TO anon USING (COALESCE("IsActive", true) = true);

-- RPCs: 前端透過 SECURITY DEFINER 寫入紀錄，不直接開放 anon insert policy。
CREATE OR REPLACE FUNCTION public."P102AddSearchEvent"(p_keyword text, p_result_count integer, p_matched_by text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public."TblP102SearchEvents" ("Keyword", "ResultCount", "MatchedBy")
  VALUES (p_keyword, p_result_count, p_matched_by);
END;
$$;
GRANT EXECUTE ON FUNCTION public."P102AddSearchEvent"(text, integer, text) TO anon;

CREATE OR REPLACE FUNCTION public."P102AddSearchFailure"(p_keyword text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public."TblP102SearchFailures" ("Keyword") VALUES (p_keyword);
END;
$$;
GRANT EXECUTE ON FUNCTION public."P102AddSearchFailure"(text) TO anon;

CREATE OR REPLACE FUNCTION public."P102AddSpaceViewEvent"(p_space_no text, p_space_name text, p_campus_no text, p_floor_map_pic text, p_campus_map_pic text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public."TblP102SpaceViewEvents" ("SpaceNo", "SpaceName", "CampusNo", "FloorMapPic", "CampusMapPic")
  VALUES (p_space_no, p_space_name, p_campus_no, p_floor_map_pic, p_campus_map_pic);
END;
$$;
GRANT EXECUTE ON FUNCTION public."P102AddSpaceViewEvent"(text, text, text, text, text) TO anon;

CREATE OR REPLACE FUNCTION public."P102AddFeedback"(p_space_no text, p_space_name text, p_feedback_type text, p_feedback_text text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public."TblP102Feedback" ("SpaceNo", "SpaceName", "FeedbackType", "FeedbackText")
  VALUES (p_space_no, p_space_name, p_feedback_type, p_feedback_text);
END;
$$;
GRANT EXECUTE ON FUNCTION public."P102AddFeedback"(text, text, text, text) TO anon;

-- 統計 Views
CREATE OR REPLACE VIEW public."ViewP102PopularKeywords" AS
SELECT "Keyword", COUNT(*) AS "SearchCount", AVG("ResultCount") AS "AverageResultCount", MAX("CreatedAt") AS "LastSearchedAt"
FROM public."TblP102SearchEvents"
GROUP BY "Keyword"
ORDER BY "SearchCount" DESC;

CREATE OR REPLACE VIEW public."ViewP102SearchFailures" AS
SELECT "Keyword", COUNT(*) AS "FailureCount", MAX("CreatedAt") AS "LastFailedAt"
FROM public."TblP102SearchFailures"
GROUP BY "Keyword"
ORDER BY "FailureCount" DESC;

CREATE OR REPLACE VIEW public."ViewP102PopularSpaces" AS
SELECT "SpaceNo", "SpaceName", COUNT(*) AS "ViewCount", MAX("CreatedAt") AS "LastViewedAt"
FROM public."TblP102SpaceViewEvents"
GROUP BY "SpaceNo", "SpaceName"
ORDER BY "ViewCount" DESC;
